name: Check
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install deps
        run: npm ci
      - name: lint
        run: npm run lint